---
- hosts: InstallBaculaAgent
  vars_files:
    - vars.yml
    - basic.yml
  connection: ssh
#  strategy: free
#  strategy: debug
  gather_facts: no
#  gather_facts: yes
  become: yes
  become_method: sudo
  become_user: root
  remote_user: root

  tasks:
    - name: Test connection
      ping:

#    - debug: var=ansible_distribution

    - name: Pause play to interact with the servers
      pause: prompt="This playbook paused... Hit <ENTER> to continue or <CTRL-C A> to abort"

#    - name: New task to interact with the servers


#    - name: Audit Linux systems/services for correct backup process(Bacula Bare-Metal)
#      command: /etc/bacula/scripts/audit_linux_system.sh || /bin/true
#      args:
#          executable: /bin/bash

  handlers:
    - include: handlers.yml
